name: Jogo Snake nos commits

on:
  push:
    branches:
      - main

jobs:
  generate_snake:
    runs-on: ubuntu-latest 
    steps:
      - name: generate-snake-game-from-github-contribution-gri
        uses: Platane/snk@v3.2.0
        
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Executar Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Lucasfranken131
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
